# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

stages:
  - stage: build_test_publish
    displayName: Build, test and publish
    jobs:
    - job: build

      pool:
        vmImage: 'windows-latest'

      variables:
        solution: 'BulkyBookWeb/BulkyBook.sln'
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'

      steps:
      - task: NuGetToolInstaller@1

      - task: NuGetCommand@2
        inputs:
          restoreSolution: '$(solution)'

      - task: FileTransform@1
        inputs:
          folderPath: '$(System.DefaultWorkingDirectory)/'
          fileType: 'json'
          targetFiles: 'BulkyBookWeb/BulkyBookWeb/appsettings.json'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

    - job: test
      dependsOn: build

      pool:
        vmImage: 'windows-latest'

      variables:
        solution: 'BulkyBookWeb/BulkyBook.sln'
        buildPlatform: 'Any CPU'
        buildConfiguration: 'Release'
      steps:
      - task: VSTest@2
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

    - job: publish
      dependsOn: test

      pool:
        vmImage: 'windows-latest'

      steps:
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)' 
          artifactName: drop

  - stage: deploy_to_staging
    displayName: Deploy to Staging
    dependsOn: build_test_publish
    jobs:
    - deployment: Deploy
      pool:
        vmImage: 'windows-latest'
      variables:
        ASPNETCORE_ENVIRONMENT: 'Staging'
      environment: Staging
      strategy:
        runOnce:
          deploy:
            steps:

            - task: DownloadPipelineArtifact@2
              inputs:
                source: 'current'
                artifact: 'drop'
                path: '$(System.DefaultWorkingDirectory)'

            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'Azure for Students(312f9249-0bf4-4c1e-8b80-7b5d443de257)'
                appType: 'webApp'
                WebAppName: 'BulkyBookRay-staging'
                packageForLinux: '$(System.DefaultWorkingDirectory)/BulkyBookWeb.zip'
                SlotName: 'Staging'
        
  - stage: deploy_to_production
    displayName: Deploy to Production
    dependsOn: deploy_to_staging
    jobs:
    - deployment: Deploy
      pool:
        vmImage: 'windows-latest'
      environment: Production
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                source: 'current'
                artifact: 'drop'
                path: '$(System.DefaultWorkingDirectory)'

            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'Azure for Students(312f9249-0bf4-4c1e-8b80-7b5d443de257)'
                appType: 'webApp'
                WebAppName: 'BulkyBookRay'
                packageForLinux: '$(System.DefaultWorkingDirectory)/BulkyBookWeb.zip'